CREATE TABLE SCHEDULE
(
    SCHEDULE_ID       UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    REGISTRATION_DATE DATE,
    UPDATE_AT         DATE,
    ACTIVE            BOOLEAN,
    USER_ID           UUID,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES _USER(USER_ID)
);