CREATE TABLE SCHEDULE_TODO
(
    SCHEDULE_ID UUID NOT NULL,
    TODO_ID     UUID NOT NULL,
    PRIMARY KEY (SCHEDULE_ID, TODO_ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (SCHEDULE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TODO_ID) REFERENCES TODO (TODO_ID) ON DELETE CASCADE
);