server:
  port: 8780
  error:
    include-message: always
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/postgres
    username: rafaEz
    password: Ez@1234
  flyway:
    baseline-on-migrate: true
management:
  security:
    enabled: false
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351